# Generated by Django 4.1.7 on 2023-06-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_prato_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
