# Generated by Django 4.2.2 on 2023-06-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churras', '0004_prato_foto_prato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('Churrasco', 'Churrasco'), ('Sobremesa', 'Sobremesa')], max_length=100, verbose_name='Categoria'),
        ),
        
    ]
