# Generated by Django 4.2.2 on 2023-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0005_alter_prato_categoria_alter_prato_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=15, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('Entradas', 'Entradas'), ('Churrasco', 'Churrasco'), ('Sobremesa', 'Sobremesa')], max_length=100, verbose_name='Categoria'),
        ),
    ]
