# Generated by Django 4.2.2 on 2023-06-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0006_categoria_alter_prato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churras.categoria'),
        ),
    ]
